### ISSUE TITLE
Easier way to add tags

### ISSUE THREAD

**Issue by JedMeister** [alonswartz/notesium#43]
This "issue"/feature request relates to the web UI - but is likely relevant to the CLI editor too. I'll use 'tags' to refer to what you seem to call "labels" in the readme. But perhaps I misunderstand what you mean by labels?

----

**TL:DR** I can't see how to add multiple tags to a note? My suspicion is that others may be looking for this.

----

What I'm looking for is somewhat already provided by existing features - which are cool and useful as is. However they're not quite what I'm looking for. I.e.:

- **note cross linking** - having to cross link every note that is relevant to any/every other note is a friction, so I'm not doing it much at all. Being able to just add multiple tags to each new note (somewhere/somehow) feels quicker, easier and a more "intuitive" way to automagically group relevant notes together. E.g. Firefox bookmark style tagging.

- **title** - is the title intended to be a space separated list of tags? My default (and my desire) is to be able to give a plain english title, one that is descriptive, but not explicit about full content.

- **search** - is useful as is, but the results are too noisy for what I'm looking for.

**Comment by alonswartz** [comment]
## Labels

> TL:DR I can't see how to add multiple tags to a note?

> note cross linking - having to cross link every note that is relevant to any/every other note is a friction, so I'm not doing it much at all. Being able to just add multiple tags to each new note (somewhere/somehow) feels quicker, easier and a more "intuitive" way to automagically group relevant notes together. E.g. Firefox bookmark style tagging.

As discussed in the [README](https://github.com/alonswartz/notesium?tab=readme-ov-file#notes-with-one-word-titles-are-considered-labels), notesium supports the concept of labels, but there is no special label syntax. Instead, a label is just a regular note, and only considered a label if its title is one-word.

There is no limit to the amount of a links a note can have - so, if you want have multiple labels, you would just link to those label notes. Where you specify those links is up to you.

You could add the label links at the top of the body, for example
```
# never split the difference

[books](625bdd26.md) [negotiation](64392126.md)

...
```

And or they could be inline, [for example](https://raw.githubusercontent.com/alonswartz/notesium/master/tests/fixtures/64214a1d.md):
```
# richard feynman

richard phillips feynman was an american theoretical [physicist](642146c7.md), known for his work in ...
```

There is no need to manually cross link every note due to backlink support, meaning you wouldn't need to manually link to each *book* from the `book` note. Having just one link is sufficient to create the linkage, no matter the direction.

You can see linkages in multiple ways:
- The `note` side-panel displays LinkTrees ([screenshot - right sidepanel Incoming Links](https://camo.githubusercontent.com/7c1f73b0038650919f5dfb042f71dc08b9a89b1247e709f087dac934a8bd9d19/68747470733a2f2f7777772e6e6f74657369756d2e636f6d2f696d616765732f73637265656e73686f742d313730343937363633372e706e67)).
- By using the `label` and `notes-list` side-panels in conjunction. By clicking a label it will auto-filter the notes-list.
- Note list dialog with prefixed labels, and manually filtering for the label you want ([screenshot](https://camo.githubusercontent.com/24ea8b1e09d5edf4ba98a21b58aed083a3454cc02df89ec13d42268a7dcbf11a/68747470733a2f2f7777772e6e6f74657369756d2e636f6d2f696d616765732f73637265656e73686f742d313730323930373230312e706e67)).
- Graph view (either global or note-specific)

Just for completeness, auto-formatted links can be easily inserted while editing a note by typing `[[` - which will bring up the `LinkInsertion` dialog.

Does that address the question/comment, or did I misunderstand?

## Titles

> title - is the title intended to be a space separated list of tags? My default (and my desire) is to be able to give a plain english title, one that is descriptive, but not explicit about full content.

[Titles](https://github.com/alonswartz/notesium?tab=readme-ov-file#titles-are-inferred-from-the-first-line) *should* be plain text and descriptive, not a list of tags. Ideally they should be in markdown H1 format, for example:
```
# never split the difference
```

## Search

> search - is useful as is, but the results are too noisy for what I'm looking for.

Could you clarify what mean, and how you think it could be "less noisy" or what you would expect?

**Comment by JedMeister** [comment]
>  label is just a regular note, and only considered a label if its title is one-word.

> You could add the label links at the top of the body, for example [...]

> or they could be inline

Ah ok, what I'm asking for is already possible - just via a mechanism that I missed/didn't get!?  With that context, using 'labels' makes way more sense than 'tags'!

Looking at the bits I've quoted, I'm 99% sure I get it. To be 100%, let me summarise my understanding:

A label is "created" by:
- a note with a single word title, with links to/from it; or
- a single word link to another note, anywhere within a note

> There is no need to manually cross link every note due to backlink support, meaning you wouldn't need to manually link to each book from the book note. Having just one link is sufficient to create the linkage, no matter the direction.

Ok,  I'll have a bit of a play to ensure that I understand correctly.

Although I don't really get what you mean by "book"? Sounds like there is something else I missed...

> Just for completeness, auto-formatted links can be easily inserted while editing a note by typing [[ - which will bring up the LinkInsertion dialog.

Ah ok, I missed that. Again, I'll have more of a play and see how I go.

Only one last label related thing:

How do you create new labels if other relevant/related notes don't yet exist?

IIUC a single new label could be created by giving it a single word title. But what about creating multiple new labels for a single note?

IIUC you'd need to create multiple new notes, one for each label. Then link them to/from the original note - I guess from the original note would be better?!

If I'm right, IMO it'd be nice to have a quicker/easier way to create new tags. It probably applies less when you already have lots of notes. But when you're starting and only have a few notes, I imagine that may feel a bit clunky.

Only a wishlist item though...

> >   search - is useful as is, but the results are too noisy for what I'm looking for.
>
> Could you clarify what mean, and how you think it could be "less noisy" or what you would expect?

Search is fine for actually searching.

I just missed/misunderstood lots of the above and was noting that search was way too noisy to achieve what I wanted.

Turns out that I just didn't get that what I was after already existed. I just didn't get how it worked. I.e. a knowledge gap - mostly because I'm a shocker for not reading docs properly...

----

TBH it feels a little I've wasted your time (and mine too). I do appreciate your explanation, although next time please feel free to just tell me to RTFM first! :) A link to the relevant doc paragraph might be useful though. ;) I'll come back if I still don't get it.

**Comment by JedMeister** [comment]
I was going to repurpose this issue (hence the subject retitle) - to a related new feature request. But decided it's cleaner to just close this and start a fresh issue - #45
